FROM debian:jessie

MAINTAINER Bryzgalov Peter <peterbryz@yahoo.com>

# Install Python and Jupyter

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    checkinstall bzip2 ca-certificates sudo locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y gfortran && apt-get -y autoremove

RUN apt-get install -y libtiff5-dev libjpeg-dev && apt-get -y autoremove
RUN apt-get install -y python-setuptools python-pip
RUN apt-get install -y python-numpy python-scipy python-pandas \
    python-tk && apt-get -y autoremove

RUN /usr/bin/python --version

RUN pip install -U pip
RUN pip install -U nose
RUN pip install -U matplotlib
RUN pip install -U Pillow
RUN pip install -U Theano
RUN pip install -U keras
RUN pip install -U tensorflow
RUN pip install -U html5lib==1.0b8
RUN pip install -U jupyter

WORKDIR /root
CMD jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=""
