FROM arm64v8/ubuntu:16.04
MAINTAINER Bryzgalov Peter <peterbryz@yahoo.com>
ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils pkg-config libblas-dev liblapack-dev libatlas-base-dev gfortran \
    g++ git wget vim \
    python-h5py python-pil python-pip python-protobuf python-scipy \
    python-gevent python-matplotlib \
    python-numpy python-dev python-nose  \
    vim wget  \
    && apt-get clean

RUN pip install -U pip setuptools
RUN pip install Cython
WORKDIR /root
RUN apt-get install -y cmake
RUN cmake --version
RUN git clone https://github.com/Theano/libgpuarray.git
WORKDIR libgpuarray

# Use gpuarray 0.6.2
RUN git checkout tags/v0.6.2 -b v0.6.2
RUN pip install -U prettytable Mako pyaml
RUN mkdir Build
WORKDIR Build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release
RUN make
RUN make install
WORKDIR ..
RUN python setup.py build
RUN python setup.py install
RUN ldconfig
WORKDIR ..
RUN pip install -U nose pygpu
RUN pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git --user
RUN pip install -U keras
RUN pip install -U jupyter[notebook]